#!/usr/bin/env python3
"""Export the draft deck's full content as reviewable Markdown.

Writes docs/presentation/slides_draft.md: every slide's title, callout,
bullets, exhibit reference with its Figure/Notes caption, speaker script,
and [Sources] line, in slide order. Content is read from the generator's
own SLIDES/CHARTS/FIGS/SOURCES structures - the same structures the built
PPTX is generated from, and whose speaker notes the generator's post-build
self-check verifies against the saved package on every build. Re-run after
any deck change (alongside scripts/build_slides_draft.py).
"""
import importlib.util
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location(
    "build_slides_draft", REPO / "scripts" / "build_slides_draft.py")
gen = importlib.util.module_from_spec(spec)
spec.loader.exec_module(gen)

OUT = REPO / "docs" / "presentation" / "slides_draft.md"

lines = [
    "<!-- Generated by scripts/export_deck_text.py - do not edit by hand.",
    "     Text mirror of docs/presentation/slides_draft.pptx for content",
    "     review; the generator's post-build self-check ties the two. -->",
    "",
    "# Beyond a Good Story - draft deck, full content",
    "",
]

for i, (title, sub, big, bullets, chart, script, eyebrow) in enumerate(gen.SLIDES, 1):
    label = f"Slide {i}" if i <= 10 else f"Appendix A{i - 11}" if i > 11 else "Appendix divider"
    lines.append(f"## {label} - {title if title else '(closing / divider)'}")
    lines.append("")
    lines.append(f"*Eyebrow:* `{eyebrow}`")
    if sub:
        lines.append(f"*Subtitle:* {sub}")
    if big:
        num, unit = big.split("|")
        lines.append(f"*Callout:* **{num.strip()}** {unit.strip()}")
    lines.append("")
    for b in bullets:
        lines.append(f"- {b}")
    if bullets:
        lines.append("")
    if chart and i in gen.CHARTS:
        fig = gen.FIGS.get(i)
        lines.append(f"*Exhibit:* `docs/presentation/charts/{gen.CHARTS[i]}` ({chart})")
        if fig:
            no, name, notes = fig
            lines.append(f"*Caption:* **Figure {no}.** {name}")
            lines.append(f"*Notes:* {notes}")
        lines.append("")
    if i == 10:
        lines.append("*Closing quote (rendered on-slide):* " + " ".join(gen.CLOSING_LINES))
        lines.append("")
    lines.append(f"> **Script** - {script}")
    lines.append(">")
    lines.append(f"> **[Sources]** {gen.SOURCES.get(i, gen.DEFAULT_SOURCE)}")
    lines.append("")

OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {OUT} ({OUT.stat().st_size} bytes, {len(gen.SLIDES)} slides)")
